### ISSUE TITLE
SP版バーナーのサイズ調整

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#124]
SP版バーナーのサイズが大きいため、見切れてしまっています。複数バーナーが入ってもパッとみれるようにサイズの調整のほどお願いいたします。

**Comment by chelproc** [comment]
バナーの大きさは縦幅固定、横幅可変となっています。登録されているデータのアスペクト比を変えることで大きさの調整ができます！

**Comment by KanjiSuzuki0321** [comment]
承知いたしました！
