### ISSUE TITLE
structured content について、一文の横幅を制限

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#125]
structured content について、一文の横幅を制限したいです。文字数は、contentと同じでお願いいたします。

**Comment by chelproc** [comment]
@KanjiSuzuki0321 すみません！こちら確認不足でした！
ここでいうstructured contentとは固定ページ（/static/[slug]）のことで合ってますでしょうか？？
そして一文の横幅というのは、コンテンツの横幅という認識で大丈夫でしょうか？？ちなみに現在の静的ページのコンテンツの横幅は下みたいに定義されてます！

https://tailwindcss.com/docs/container
![image](https://user-images.githubusercontent.com/45363260/117087635-0c19aa00-ad8b-11eb-916e-fca68602212a.png)

各行例えば `xl (1280px) | max-width: 1280px;` は `画面の横幅が1280px以上なら、コンテンツの横幅を最大1280pxで表示する` という意味になります。下のルールほど優先度高いです！

画面の横幅が何pxくらいのときの大きさを調節したらよさそうですか？

ちなみに現在はサイト内で上記設定になっている部分となっていない部分があったりしますので、この機に全部統一できるようにしようと思います！

ちなみに画面の横幅はChromeでは下みたいに確認できます！
https://sole-color-blog.com/blog/659/

**Comment by KanjiSuzuki0321** [comment]
すみません、固定ページ（/static/[slug]）のことです！

モニターで見た際に、少し横幅がワイドに映ったので、そこを狭めて欲しいという意図でのissueでした。
ですが上記を見た感じ、現状問題なく対応されている気がします。すみません。

全体的に、現在の卒業生インタビューがいい感じですので、それに全て揃えていただきたいです。
