### ISSUE TITLE
structured content内で画像にURLを埋め込めるようにする

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#136]
structured content内で画像にURLを埋め込めるようにしていただきたいです。

**Comment by chelproc** [comment]
@KanjiSuzuki0321 お疲れ様です！画像にURLを埋め込むというのはどういったユースケースを想定されていますでしょうか？？
他の記事へのリンクということで問題ないでしょうか？それであれば現状の画像にリンクを埋め込むというよりはきちんと構造化すべきかなと思いまして

**Comment by KanjiSuzuki0321** [comment]
一応こちらでも。他の記事へのリンクという意図です！

**Comment by chelproc** [comment]
承知しました！ありがとうございます！！

**Comment by chelproc** [comment]
とりあえずそれっぽいものを作ってみました！確認いただけると幸いですm(__)m

**Comment by KanjiSuzuki0321** [comment]
ありがとございます！
/Embeded Imageからでしょうか？
また、記事はstaticでしょうか？

**Comment by KanjiSuzuki0321** [comment]
すみません！
/add link
ですね！試してみます。ありがとうございます！

**Comment by KanjiSuzuki0321** [comment]
とてもいい感じでした！
ありがとうございます！ 😊
