### ISSUE TITLE
バーナーのサイズ変更

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#138]
バーナーのサイズを変更していただきたいです。今からの変更となってしまいすみません。。。
理想としては、挿入したバーナーのサイズによって、背景黒字が自動で調整されるのが理想です。
それが難しい場合は、この[サイト](https://www.concord-career.com/)と全く同じサイズにしたいです。その場合、横に並列するバーナーの数は、3個で固定で構いません。
Priorityに関しては、コメントします

**Comment by KanjiSuzuki0321** [comment]
すみいません、こちらクライアントの関係上、可能であれば最優先で修正お願いしたいのですが、可能でしょうか？

**Comment by chelproc** [comment]
すみません！もう少し情報をいただけると嬉しいです！現代のWebデザインではあらゆる画面幅をもつ端末を想定しなければなりません！なので、
* 画像のアスペクト比
* 画像の数
* 画面幅
それぞれに応じてバナーの表示領域がどのように変化するのかが決まっていないと厳しいです＞＜
特に画面幅に関しては境界となる大きさが重要なのでその点を意識していただけるとうまくいくと思います！

**Comment by KanjiSuzuki0321** [comment]
すみません。こちら、くどくなるというご指摘はごもっともでしたので、一度保留でお願いいたします。

**Comment by chelproc** [comment]
承知しました！ありがとうございますm(__)m

**Comment by chelproc** [comment]
カルーセルの導入と同時にバナーを大幅に改善する変更をした (#187)
