### ISSUE TITLE
staticのstructured contentで、空白行を入力できるようにする

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#139]
staticのstructured contentで、空白行を入力できるようにしたいです。
現状、datoCMS上で空白行を入れても、記事に反映されません。

**Comment by chelproc** [comment]
モダンなリッチテキストエディタでは、改行と段落を厳密に区別しています！
下の記事を読んでみてください！
https://www.infact1.co.jp/staff_blog/webmarketing/42554/

「空行」はデザイン上の余白なので、コンテンツ内で指定すべき事項ではありません（サイト全体のテーマを変更した際にデザインが崩れる原因になります）！
見出しや水平線で対応できないか検討してください！

**Comment by chelproc** [comment]
DatoCMSでは「改行」はShift+Enter、「段落区切り」はEnterで挿入できます。Wordと同じ操作なので比較的直観的に操作できるかと！

**Comment by KanjiSuzuki0321** [comment]
わかりました！ありがとうございます！
