### ISSUE TITLE
画像にリンクを埋め込む

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#145]
記事内部の画像にリンクを埋め込みたいです。画像をタップすると、指定したURLに遷移するイメージです。前回のご依頼とは別で、こちらもお願いしたいです。
ユースケースとしては、例えば塾講師募集の広告で、応募画面への遷移は、文字ではなく画像にURLを埋め込んだ方が繊維率が高いです。

**Comment by chelproc** [comment]
お疲れ様です！記事内部の画像なのですが、あくまで文章を補足するための要素として用意しており、UIの一部として使用されることは想定していません。
というのも、好きに画像を埋め込めるという仕様は記事執筆者にあまりにも大きな裁量を与えてしまうことになり、全体としてのデザインの崩れを招きかねないからです。

重要なのはむしろユースケースで、

> 例えば塾講師募集の広告で、応募画面への遷移は、文字ではなく画像にURLを埋め込んだ方が繊維率が高いです。

ということであれば、応募画面への遷移ボタンを作るためのブロックを用意することで対応できませんか？？
いったんユースケースを整理していただけると、何が本質的に必要なのかが見えてくるかと思います！

**Comment by KanjiSuzuki0321** [comment]
ありがとうございます！ご指摘大変助かります🙏
おっしゃる通りですので、下記の「企業についてより詳し知る」のような、ボタンを設置するためのブロックをご用意いただけると幸いです。

<img width="643" alt="スクリーンショット 2021-05-23 16 12 47" src="https://user-images.githubusercontent.com/80612908/119251482-bc880a80-bbe1-11eb-9055-42cbb20da228.png">

**Comment by chelproc** [comment]
なるほど:eyes: [CTA](https://webtan.impress.co.jp/g/cta)のことかと推察しました！

一旦

* ボタンのテキスト
* 遷移先URL（新しいタブで開く）

を設定できるブロックを作ろうかと思います！

ちなみに上記のようなデザインだとCTAとしては少々地味かなあという感じがするのですが、何かデザイン的な要望があったらお伝えいただければ！

**Comment by KanjiSuzuki0321** [comment]
ありがとうございます！よろしくお願いします。

デザインに関しては、そちらで問題ありません！そちらは、static/internship/eventで作成お願いしたいです。internship/eventについては同じ内容をすでに他のissueでお願いしています。

ーーーー補足ーーーーー
また、インターン・イベントについては、下記のようなCTAの挿入をお願いしています。
すでにお願いしたボタンの埋め込みについては、全ての記事タイプで可能にしたい一方で、このCTAハインターン・イベントにさえあれば問題ございません。

<img width="755" alt="スクリーンショット 2021-05-25 18 19 08" src="https://user-images.githubusercontent.com/80612908/119473016-b599fd00-bd85-11eb-91b7-b6ddce8f0ec4.png">

**Comment by KanjiSuzuki0321** [comment]
こちら、priority highest でお願いいたします！
