### ISSUE TITLE
サムネと記事上部の背景画像を別々に設定

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#146]
サムネと記事上部の背景画像を別々に設定できるようにしてほしいです。優先度は、static→intern/event→graduatesの順でお願いします！

**Comment by kaing46** [comment]
@KanjiSuzuki0321 
DatoCMSのStaticPage,Event,GraduateArticleにHero Imageというフィールドを追加したので、そこの画像を記事上部の背景に表示できます。

**Comment by KanjiSuzuki0321** [comment]
素早いご対応ありがとうございます！
