### ISSUE TITLE
インターン・イベント記事タイプの末尾にLINEへの導線設計

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#196]
インターン・イベント記事タイプの末尾にLINEへの導線設計をしたいです。
こちらでデザインをご用意しますので、そちらを元に実装いただく予定です！（ということで、当面は僕の宿題となります。忘れたら困るのでmemoがてら、、、）
意図としては、Twitterから流入したサイト訪問者のうち、東大生だけにLINE登録をしていただくことです。

**Comment by KanjiSuzuki0321** [comment]
こちらにデザイン置いときます！
https://drive.google.com/drive/folders/1bI24XP7NpEm7ZPRjEhlsFXjdjpvIrMLr?usp=sharing

**Comment by integral0523** [comment]
@KanjiSuzuki0321 ut.code();の関本です。Googleドライブのファイルへのアクセス権限リクエストさせていただいたので承認お願いします。

**Comment by KanjiSuzuki0321** [comment]
@integral0523 
先程許可いたしました！

**Comment by chelproc** [comment]
こちらなのですが、デザインデータ内の画像が埋め込み設定になっていないらしく、閲覧ができない状態です。お手数ですがご確認いただけないでしょうか。

![image](https://user-images.githubusercontent.com/45363260/145700514-8b094c0d-4cc0-46de-ae71-3d73a9d86031.png)

**Comment by KanjiSuzuki0321** [comment]
おっとすみません、
ちなみにこちら、ご希望のデータ形式などありますか？
@chelproc

**Comment by chelproc** [comment]
@KanjiSuzuki0321 スマートフォンフレームへのはめ込み後のPNGとかだと嬉しいです！

**Comment by KanjiSuzuki0321** [comment]
承知しました！
デザイナーに確認取るので少々お待ちください！

**Comment by Kanji-Suzuki** [comment]
@chelproc 
すみません、ご連絡忘れていたのですが、上記リンクのデータを貼り替えました！

**Comment by Kanji-Suzuki** [comment]
@integral0523

**Comment by Kanji-Suzuki** [comment]
jpegも今あげますので少々お待ちください

**Comment by KanjiSuzuki0321** [comment]
https://drive.google.com/file/d/1KMQMDz-eOLrbzS08ODLRAaKN6-I_wrCU/view?usp=sharing
@chelproc
