### ISSUE TITLE
サークル記事タイプのサークル概要について、文字の大きさ・行間を調整する

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#217]
サークル記事タイプのサークル概要について、文字の大きさ・行間を調整する。

![スクリーンショット 2021-08-12 18 14 51](https://user-images.githubusercontent.com/80612908/129171491-de3dea94-fed9-4781-bbc3-d7f302cfe187.png)

**Comment by chelproc** [comment]
@KanjiSuzuki0321 
現在は本文と同じ文字サイズ＆行間になってると思いますが、どういう感じがよさそうでしょうか？？
とりあえずパディングを大きくしてみました😎

**Comment by Kanji-Suzuki** [comment]
ありがとうございます！
意図としては、気軽な気持ちで見にきた学生が、ぎちっと詰まったサークル紹介を見ると読む気をなくしそうだなと感じたためです。
追加で、行間を少し広くすること可能でしょうか？（具体的な数字がなくてすみません、、）
本文よりもさらに見やすくわかりやすいデザインにできればと思います！
