### ISSUE TITLE
アーティクルギャラリーでstatic以外のページ全てを参照できるようにしたい

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#221]
アーティクルギャラリーでstatic以外のページ全てを参照できるようにしたいです。
インターン・イベント→graduateの優先順位でお願いいたします。
意図としては、インターンを載せるにあたって、そこの代表さんのインタビューを同時に載せることがあります。
インタビューから案件への導線をつけたいです。

**Comment by kaing46** [comment]
@KanjiSuzuki0321 
こちらのアーティクルギャラリーというのは、インターンやイベントページでアーティクルギャラリーという項目を作ってそこでiインタビュー記事を参照できるようにするという形でよろしいでしょうか？
