### ISSUE TITLE
サークルページSEO settingsの自動設定

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#273]
サークルページSEO settingsを自動設定できるようにしたいです。
具体的には、

写真→

> image の一枚目

description→

> 【東大[大カテゴリー]】
> Descriptionから文字数上限まで切り取り

**Comment by chelproc** [comment]
@KanjiSuzuki0321
こちらなのですが、DatoCMSの画像配信に使われているサービスが、テキストの埋め込みに対応しているらしく、Qiitaみたいに文字を埋め込む添付画像のようなOGPが割と簡単に自動生成できるっぽいです
もとはサークルに登録されている画像を指定するということだったと思うのですが、こちらの方式はいかがでしょうか？？

![image](https://user-images.githubusercontent.com/45363260/151685149-9b0bb791-520f-4c7d-a61c-27da4801a9be.png)

**Comment by chelproc** [comment]
@KanjiSuzuki0321
こちらなのですが、DatoCMSの画像配信に使われているサービスが、テキストの埋め込みに対応しているらしく、Qiitaみたいに文字を埋め込む添付画像のようなOGPが割と簡単に自動生成できるっぽいです
もとはサークルに登録されている画像を指定するということだったと思うのですが、こちらの方式はいかがでしょうか？？

![image](https://user-images.githubusercontent.com/45363260/151685191-f02a7c31-468b-40eb-8f1a-5d39235b0057.png)

**Comment by KanjiSuzuki0321** [comment]
@chelproc 
ありがとうございます！
「サンフレンド」と検索した時に、utmapページが出てくる状態も実現したいのですが、
こちらの対処法だと実現可能でしょうか？

**Comment by chelproc** [comment]
@KanjiSuzuki0321 すみません，『「サンフレンド」と検索した時に』とは何で検索したときでしょうか？
もし「Google検索で検索した際に検索に引っかかるようにしたい」ということでしたら，それは今回の設定とは関係なく，単純にコンテンツの質不足（サークルページは基本的に内容が薄く，相互リンクもないので基本的にインデックスされません）になるので，OGPの設定は影響しないです・・・

**Comment by KanjiSuzuki0321** [comment]
はい、「Google検索で検索した際に検索に引っかかるようにしたい」です。
承知いたしました！では、twitterなどに記事をアップした際にサムネイルが表示されることが、このissueの目的になります。
本日上げていただいたDatoCMSの画像配信に使われているサービスを利用する方針でお願いします！

また、話逸れてしまいますが、サークル名をGoogle検索で検索した際に検索に引っかかるようにしたいです。
サークル以外のページであれ、サイト内部のページどこかが引用されれば、
サークル名をGoogle検索で検索した際に検索に引っかかるようにしたい、に一歩近づくのでしょうか？
コンテンツの充実は実現可能性が低いので、被リンクを増やす方針で努力しようかなと思っています。

**Comment by chelproc** [comment]
@KanjiSuzuki0321 
「コンテンツの充実なしにインデックスさせる」は不可能ですね・・・
そもそもそれができたらGoogle検索はスパムサイトだらけになっちゃいます
一応サイトマップでページの存在自体はGoogleに通知しちゃっているのですが，ほとんどインデックスされていない状態です
低品質なサークルページは検索インデックスから除外するなどの対策をしたうえで，URLの再構成等の対策が必要かなあという感じです

**Comment by KanjiSuzuki0321** [comment]
@chelproc 
すみません、サークル詳細ページのコンテンツ質向上は難しいの意図です。
サークル以外のページであれ、サイト内部のページの質が向上すれば
サークル詳細ページの検索順序を上げることは可能ですか？
また、seo上一番重要となるページは、サークル関連のページ順位を上げることになります。

**Comment by chelproc** [comment]
@KanjiSuzuki0321 
無論コンテンツの質が上がれば検索順位は上がることになります
ただGoogleアルゴリズムの問題なので保証はできないです汗

**Comment by KanjiSuzuki0321** [comment]
@chelproc 
詳細にありがとうございます！
そちらもどこかで実施をお願いしたいです。
issueを新たに立ててもよろしいでしょうか？
