### ISSUE TITLE
キャリア戦略論ホームに導入文を設置

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#276]
キャリア戦略論ホームにトップメッセージを設置していただきたいです。
「東大生のためのキャリア戦略」は、UTmap 編集部が、日本No.1の実績をもつキャリアコンサルタント・渡辺秀和⽒（（株）コンコードエグゼクティブグループCEO）を迎えて制作した特集コンテンツです。東京⼤学で⼈気を博したキャリアデザインの授業 「キャリア・マーケットデザイン」のコースディレクターを務めた渡辺秀和氏が、不透明な時代を生き抜くためのキャリア設計法を解説します。

**Comment by chelproc** [comment]
`/career-strategies`
