### ISSUE TITLE
検索時の表示タイトルを変更

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#284]
検索時の表示タイトルを変更していただきたいです。

（現）ホーム | UTmap Times　
→（new）UTmap｜東大生のキャリア設計プラットフォーム

**Comment by chelproc** [comment]
@KanjiSuzuki0321 タイトルの中の縦棒記号は、基本的に「（右辺）というウェブサイトの中の（左辺）というページ」という意味なので、「UTmap｜東大生のキャリア設計プラットフォーム」よりは、「UTmap - 東大生のキャリア設計プラットフォーム」としたほうがベターかなと思います。いかがでしょうか？？

![image](https://user-images.githubusercontent.com/45363260/145700139-c4d356ef-14bf-4173-a3b5-98a6ea17f7d0.png)

**Comment by KanjiSuzuki0321** [comment]
ご提案ありがとうございます！
確かに仰る通りですね。そちらでよろしくお願いいたします！
