### ISSUE TITLE
全体descriptionの設定

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#285]
全体descriptionの設定をしていただきたいです。

東大生が、より良い人生を切り開き、より良い未来をつくるために、東大生活を歩む「地図」を描きたい。
UTmapは、東大生のキャリアに大きな影響をもたらす「サークル」「進学選択」「就活」という３つの意思決定をサポートします。

**Comment by inotani11** [comment]
@KanjiSuzuki0321 
お忙しい中すみません！
descriptionが何を指しているのかがわからないのですが、教えていただいてもいいでしょうか。

**Comment by KanjiSuzuki0321** [comment]
お疲れ様です！
わかりにくくてすみません、検索時の下に出てくる紹介文的なやつを指しています！

![スクリーンショット 2021-11-28 12 24 46](https://user-images.githubusercontent.com/80612908/143727634-de59d2b8-97d9-41c6-b04e-fec4ef603675.png)

**Comment by chelproc** [comment]
「全体」というと、トップページのことでよろしいでしょうか？
ちなみにGoogle検索で表示されるリンクのタイトルとその説明文はGoogleが決定しており、完全に制御することはできません。
ただある程度はコントロールすることができるので、今回はトップページの説明文（＝[descriptionメタデータ](https://developer.mozilla.org/ja/docs/Web/HTML/Element/meta/name)）を記載のものに書き換える、という対応になるかと思いますが、意図にあってますでしょうか。

**Comment by KanjiSuzuki0321** [comment]
わかりずらくて申し訳ありません。
はい、トップページを指しています。
てっきりそこは指定できるのかと思っていました、、

> 今回はトップページの説明文（＝descriptionメタデータ）を記載のものに書き換える
こちらでお願いいたします！

**Comment by chelproc** [comment]
了解です！
