### ISSUE TITLE
サークル詳細メインビジュアルのデザイン変更

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#288]
サークル詳細メインビジュアルの黒フィルターが暗いので明度をあげていただきたいです。

**Comment by Ryoengineer112358** [comment]
画像が明るくなると、文字が見えづらくなってしまうため、このままで良いと思うのですがいかがでしょうか？
![image](https://user-images.githubusercontent.com/92168295/143726692-5c4ad67c-1bf0-4bfe-8620-b6a0efa6367c.png)

**Comment by KanjiSuzuki0321** [comment]
同時に暗い印象を与えてしまうと思っていて、現時点ではそちらのデメリットの方が大きいと判断しています、、！
こちらのデザインと同じフィルター明度にしていただくことはできますか？

https://drive.google.com/file/d/1Dc0hXFfySJrXz4nEsD1AHinz-l3EXnBx/view?usp=sharing

**Comment by chelproc** [comment]
一応透明度50%→40%（Illustratorと同じ）
