### ISSUE TITLE
webサムネイルの縦横比を不変にする

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#302]
サムネイルデザインが綺麗に表示されるように、webサムネイルの縦横比を不変にしたいです。
また、現状の仕様にメリットがあって、あえてこれを選択している場合は教えてください。

**Comment by chelproc** [comment]
@KanjiSuzuki0321 Webサムネイル、といいますとどの部分になりますでしょうか？？

**Comment by KanjiSuzuki0321** [comment]
ごめんなさい、graduatesを指しています。
<img width="543" alt="スクリーンショット 2021-12-12 14 50 08" src="https://user-images.githubusercontent.com/80612908/145702001-025c9282-8884-47ec-becb-0f21e19acfb9.png">

写真のように、一部が切れて表示されてしまっています。

@chelproc

**Comment by chelproc** [comment]
確認したところ実装の問題のようです！
/clubsと同じように4:3になるよう調整しますね！
ありがとうございます:bow:

**Comment by chelproc** [comment]
と思ったら/clubsのほうは16:9になってました。どうしますか？？

**Comment by KanjiSuzuki0321** [comment]
ありがとうございます！
/graduatesの方は4:3でお願いいたします！
/clubsは16:9のままでいいかなと思うのですが、この二つのページは画像サイズを
同じんしないいといけない、などの縛りはありますか？

**Comment by chelproc** [comment]
特にないですので4:3でいきますね～
