### ISSUE TITLE
circle以外全ページの、hero imageが設定されていない時のデフォルト写真を変更

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#304]
circle以外全ページの、hero imageが設定されていない時のデフォルト写真を以下に変更お願いします。
https://drive.google.com/file/d/17F9KV-iYs4zkBYUOXcLZ-PY3r8RRPLnC/view?usp=sharing

**Comment by chelproc** [comment]
こちらもサークルだけ別とのことなのですが、サイト全体の統一感を保つにはなるべく統一したほうが良いと思うのですが、いかがでしょうか？？

**Comment by Kanji-Suzuki** [comment]
こちらもissue315と同様の理由を想定していたですが、確かにできるだけ均質な方が良いですね。
このissueはcloseでお願いします🙇‍♂️
