### ISSUE TITLE
clubsページに「ゼミ(Categiry Group)>経済学部ゼミ(Category)」を新しく追加

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#313]
clubsページに「ゼミ(Categiry Group)>経済学部ゼミ(Category)」を新しく追加していただきたいです。
「ゼミ(Categiry Group)>経済学部ゼミ(Category)」の追加と、このカテゴリーに属する団体の例（`index:325, Recordid: 85987359` ）を、datocmsに追加したのですが、サイトには反映されていないという状況です。
急で大変恐縮ですが、来週中でできると大変助かります、、！

**Comment by chelproc** [comment]
@KanjiSuzuki0321 すみません、こちらなのですがサークル検索ページでのカテゴリ一覧とタグ一覧をキャッシュしてしまっているためでした:sweat_drops:

![image](https://user-images.githubusercontent.com/45363260/146661658-2503c5c3-6197-4f7f-8656-f620a61e12dd.png)

修正しましたが、もしこのような場合、上画像のようにVercelの「Redeploy」ボタンを押してあげるとうまくいくかもしれません！参考までに。

**Comment by KanjiSuzuki0321** [comment]
承知しました！ご丁寧にありがとうございます！！
