### ISSUE TITLE
キャリアホームの卒業生インタビューで見せる記事のサムネサイズを固定する

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#350]
キャリアホームの卒業生インタビューで見せる記事のサムネサイズが、記事ごとに異なるので、固定していただきたいです。
写真ですと、右端シンプレクスが小さくなっています。
<img width="1341" alt="スクリーンショット 2022-02-14 18 44 13" src="https://user-images.githubusercontent.com/80612908/153839487-57a83d9d-a241-42be-aa17-470d6d10c6f0.png">

**Comment by KanjiSuzuki0321** [comment]
入稿写真のサイズが間違っていたみたいです。。。
すみません、こちらで修正します！

**Comment by chelproc** [comment]
いえ、サイズはアプリケーション側でも調整するようプログラムするのが普通なので、バグになると思います！
再オープンしますね
