### ISSUE TITLE
[特設ページ]✖️で遷移前ページに戻る仕様を作成いただきたです。

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#382]
仕様書「グローバルメニュー」に準じて、 押すとデザインページが表示→✖️でその前に戻る仕様を作成いただきたです。

**Comment by chelproc** [comment]
すみません、こちらに関しては実装を省略させていただけないでしょうか。

この辺が参考になります（割と有名なUIデザインについてのガイドラインです）
https://material.io/design/navigation/understanding-navigation.html#reverse-navigation

この類のナビゲーションは「This type of navigation is typically provided by the operating system or platform. Individual platforms define how it behaves and how users can access that functionality.」とされています。独自で実装することも不可能ではないのですが、検索エンジンや外部リンクからの流入の場合を考えると挙動に一貫性が取れなくなってしまいます。

**Comment by KanjiSuzuki0321** [comment]
承知いたしました！
ご丁寧にありがとうございます。
では、とりいそぎこの実装は見送りでお願いします。
