### ISSUE TITLE
【インターン詳細ページ】

### ISSUE THREAD

**Issue by Yoshi710** [ut-code/utmap-times#399]
応募条件の部分と求める人物像の部分が箇条書きできない

**Comment by Yoshi710** [comment]
![image](https://user-images.githubusercontent.com/81516618/167348464-cf61d091-5189-49e4-b73f-10a1f33a2392.png)

**Comment by kaing46** [comment]
@Yoshi710 
確認したところ、箇条書きできているところがあると思うのですが、こちら解決しましたでしょうか？

**Comment by Yoshi710** [comment]
> 

確認に時間を要してしまい、申し訳ございません！
こちら確認が完了し、解決されておりました。
修正ありがとうございます！
