### ISSUE TITLE
予約投稿できるように

### ISSUE THREAD

**Issue by inotani11** [ut-code/utmap-times#63]

**Comment by KanjiSuzuki0321** [comment]
ごめんなさい、やり方がわかりませんでした...

**Comment by chelproc** [comment]
すみません、Clubモデルのほうは有効化されていたのですが、NewsとGraduateArticleのほうはSaveボタンを押したらすぐにPublishedになる設定になってました。
両モデルについてSaveボタンを押してからPublishedにするまで反映されない設定にしたので、これで予約投稿できるようになると思います。

以下の画像みたいな感じです。おそらく #64 も同じだと思うので、大丈夫そうなら2つのissueをclose（下のボタンです）していただけると嬉しいです！
![image](https://user-images.githubusercontent.com/45363260/111157676-83785c00-85da-11eb-825f-8613532d037d.png)

**Comment by KanjiSuzuki0321** [comment]
できそうです！
すみません、おそらくですが僕の権限だとcloseできないです。。。
