### ISSUE TITLE
記事文面の横幅が一定以上にならないように調整

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#84]
記事文面の横幅が一定以上にならないようにしたいです。今は無限に横に広がるような状態になっており、見栄えが良くないです。横のmax45文字くらいを想定しています。

**Comment by chelproc** [comment]
記事の種類としてはどちらでしょうか？
少なくともサークルに関しては制限がかかっていると思います！URLとスクリーンショット（クリップボードにある状態でCtrl / Cmd + Vで行けます）頂けると嬉しいです！

**Comment by KanjiSuzuki0321** [comment]
pc版の卒業生インタビュー、どこにも属さないページについてです！どこにも属さないページが3/24までに実装可能であれば、どこにも属さないページの修正を、3/24までに実装が難しそうであれば、卒業生インタビューの調整を先にお願いします。前者の場合は、本件の修正も含めて3/24まででお願いしたいです。

手元にパソコンがないのでお昼にスクショ送ります！

**Comment by kaing46** [comment]
@KanjiSuzuki0321 
卒業生インタビュー、どこにも属さないページの記事本文横幅の最大値を少し小さくしましたが、このぐらいで大丈夫でしょうか？確認したところ52文字ぐらいが最大になりそうなんですが、、、

**Comment by KanjiSuzuki0321** [comment]
@kaing46 
大丈夫です！ありがとうございます！
その他問題なければ、closeお願いします。
