### ISSUE TITLE
OGP画像の表示

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#85]
リンクを添付したときにこのように画像と共に表示させたいです。https://twitter.com/QuizKnock/status/1371355610239823872?s=20

* [x] 固定ページ ( @inotani11 )
* [x] 卒業生インタビュー  ( @kaing46 )
* [x] サークル ( @inotani11 )

DatoCMSのContent TypeにSEO Meta Tagsというのがあるのでそれを利用する

![image](https://user-images.githubusercontent.com/45363260/111894599-61099700-8a4f-11eb-867c-7bc743d9a388.png)

**Comment by chelproc** [comment]
OGP画像の表示ですね。優先度的にはどの記事の種類からでしょうか？

**Comment by KanjiSuzuki0321** [comment]
卒業生インタビュー→どこにも属さないページ
でお願いします！サークルは必要ありません！
