### ISSUE TITLE
place, scheduleが反映されていない

### ISSUE THREAD

**Issue by KanjiSuzuki0321** [ut-code/utmap-times#93]
サークル詳細ページですが、DatoCMSにあるplace, scheduleの項目が、サイトに表示されていません。

**Comment by chelproc** [comment]
反映される前に1分ほどキャッシュされるので待ってみると良いと思います！

**Comment by KanjiSuzuki0321** [comment]
いえ、今更気づいたのですが、この2項目が表示される部分がそもそもありません！
ut.code(); さんですと、place:学生会館, schedule:毎週日曜午後が反映されていません。
